In [1]:
import os
import datajoint as dj

os.environ['DJ_SUPPORT_ADAPTED_TYPES'] = 'TRUE'
os.environ['DJ_SUPPORT_FILEPATH_MANAGEMENT'] = 'TRUE'
dj.config['enable_python_native_blobs'] = True

exported_nwb_dir = os.path.abspath('../temp_nwb/')

dj.config['stores'] = {
    'lfp_store': {'protocol': 'file',
                 'stage': exported_nwb_dir, # cache
                 'location': exported_nwb_dir} # same location
}
dj.config

{   'connection.charset': '',
    'connection.init_function': None,
    'database.host': 'localhost',
    'database.password': None,
    'database.port': 3306,
    'database.reconnect': True,
    'database.use_tls': None,
    'database.user': None,
    'display.limit': 12,
    'display.show_tuple_count': True,
    'display.width': 14,
    'enable_python_native_blobs': True,
    'fetch_format': 'array',
    'loglevel': 'INFO',
    'safemode': True,
    'stores': {   'lfp_store': {   'location': '/Users/edeno/Documents/GitHub/nwb_datajoint/temp_nwb',
                                   'protocol': 'file',
                                   'stage': '/Users/edeno/Documents/GitHub/nwb_datajoint/temp_nwb'}}}

In [2]:
from pipeline.ingest_nwb import run_ingest

run_ingest('../data')

Please enter DataJoint username:  root
Please enter DataJoint password:  ········


Connecting root@localhost:3306


/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'hdmf-common' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'core' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'franklab' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
LFP Info: 100%|██████████| 27/27 [00:00<00:00, 61.34it/s]
/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'hdmf-common' because it already exists
  warn("ignoring namespace '%s' because it alread

In [3]:
from pipeline.experiment import LFP

LFP()

*subject_id    *session_id    *insertion_num lfp_oid        lfp_timestamps lfp_unit     lfp_resolution lfp_conversion lfp_interval   lfp_descriptio lfp_comments  
+------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+
Bond           Bon0003        1              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        2              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        3              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        4              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        5              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        6              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        7              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        8              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        10             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        11             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        12             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        13             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
   ...
 (Total: 54)

In [26]:
from pynwb import NWBHDF5IO
from franklab_nwb_extensions import fl_extension
from pipeline.experiment import Session

import numpy as np

filter_string = "session_id = 'Bon0003'"
nwb_filename = (Session() & filter_string).fetch('nwb_filename')[0]
nwb_filename = os.path.join('../data', nwb_filename)

with NWBHDF5IO(nwb_filename, 'r', load_namespaces=True) as io:
    nwbfile = io.read()
    oid = (LFP() & filter_string).fetch('lfp_oid')[0]
    print(np.array(nwbfile.objects[oid].fields['data']))
    print(np.array(nwbfile.objects[oid].fields['timestamps']))

/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'hdmf-common' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'core' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/edeno/miniconda3/envs/nwb_datajoint/lib/python3.7/site-packages/hdmf/spec/namespace.py:456: UserWarning: ignoring namespace 'franklab' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])


[[-135  -59   79 ...    4   48  -89]
 [-108  -40   96 ...    4   46  -96]
 [ -71  -51  107 ...   -4   57 -115]
 ...
 [  49  106  170 ...   54   51   67]
 [  40   89  158 ...   13   47   42]
 [  54  113  153 ...   -2   32   30]]
[3728.9837     3728.98436667 3728.98503333 ... 6550.01050019 6550.01116686
 6550.01183353]


In [16]:
LFP()

*subject_id    *session_id    *insertion_num lfp_oid        lfp_timestamps lfp_unit     lfp_resolution lfp_conversion lfp_interval   lfp_descriptio lfp_comments  
+------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+
Bond           Bon0003        1              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        2              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        3              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        4              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        5              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        6              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        7              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        8              17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        10             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        11             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        12             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
Bond           Bon0003        13             17ead364-6b0a- seconds        volts        -1.0           1e-06          1              no description no comments   
   ...
 (Total: 54)

In [5]:
# dj.config.save_global()

In [6]:
# %debug

In [7]:
from pipeline.experiment import Subject

Subject.drop()

`nwb_experiment`.`subject` (1 tuples)
`nwb_experiment`.`session` (2 tuples)
`nwb_experiment`.`probe_insertion` (54 tuples)
`nwb_experiment`.`_l_f_p` (54 tuples)


Proceed? [yes, No]:  No
